name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install babashka
        run: |
           curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-bb
           chmod +x install-bb
           sudo ./install-bb
           rm install-bb
      - name: Run bb tests
        run: PATH=bin:$PATH bb -cp src:test:resources -m test-runner
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.07.29'
      - run: clj-kondo --lint src:resources test bin/*
  custom-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.06.21'
      - name: Install babashka
        run: |
           curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-bb
           chmod +x install-bb
           sudo ./install-bb
           rm install-bb
      - name: Check for unused vars
        run: BABASHKA_CLASSPATH=src bin/bb-unused-vars -i .github/workflows/unused-vars-to-ignore.edn  bin/* src
      - name: Check for missed docstrings
        run: BABASHKA_CLASSPATH=src bin/bb-missed-docstrings -i 'cli-options|-main' bin/* src
