name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # TODO: Consider switching to DeLaGuardo install
      - name: Install babashka
        run: |
           curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-bb
           chmod +x install-bb
           sudo ./install-bb
           rm install-bb
      - name: Run bb tests
        run: PATH=$PWD/bin:$PATH bb test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1165

      - run: clojure -M:clj-kondo --lint src bin/* test
  custom-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install babashka
        run: |
           curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-bb
           chmod +x install-bb
           sudo ./install-bb
           rm install-bb
      # TODO: Re-enable or replace with carve that has better support for bb.edn usage or ignoring a regex of ns
      # - name: Check for unused vars
      #   run: bin/bb-unused-vars -i .github/workflows/unused-vars-to-ignore.edn  bin/* src
      - run: bb --config dev-bb.edn lint:large-vars
      - run: bb --config dev-bb.edn lint:ns-docstrings
      - run: bb --config dev-bb.edn lint:minimize-public-vars

      # TODO: Re-enable or replace when there is more docstrings
      # - name: Check for missed docstrings
      #   run: bin/bb-missed-docstrings -i 'cli-options|-main' bin/* src
