name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Babashka test
        uses: liquidz/babashka-test-action@v1
        with:
          source-paths: 'src'
          test-paths: 'test'
          test-file-pattern: '_test.clj$'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.06.21'
      - run: clj-kondo --lint src test bin/*
