name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository for Clojure
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-
      - name: Install babashka
        run: |
           curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-bb
           chmod +x install-bb
           sudo ./install-bb
           rm install-bb
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: 1.10.1.469
      - name: Install deps.edn
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        run: echo "::set-env name=DEPS_EDN_PATHS::$(clojure -Spath -Sdeps '')"
      - name: Run bb tests
        run: PATH=bin:$PATH BABASHKA_CLASSPATH=src:$DEPS_EDN_PATHS bb -cp src:test:test/resources -m test-runner
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.07.29'
      - run: clj-kondo --lint src test bin/*
  custom-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.06.21'
      - name: Install babashka
        run: |
           curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-bb
           chmod +x install-bb
           sudo ./install-bb
           rm install-bb
      - name: Check for unused vars
        run: BABASHKA_CLASSPATH=src bin/bb-unused-vars -i .github/workflows/unused-vars-to-ignore.edn  bin/* src
      - name: Check for missed docstrings
        run: BABASHKA_CLASSPATH=src bin/bb-missed-docstrings -i 'cli-options|-main' bin/* src
