name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Babashka test
        uses: liquidz/babashka-test-action@v1
        with:
          source-paths: 'src:resources'
          test-paths: 'test'
          test-file-pattern: '_test.clj$'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.06.21'
      - run: clj-kondo --lint src:resources test bin/*
  custom-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2020.06.21'
      - name: Install babashka
        run: |
           curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install -o install-bb
           chmod +x install-bb
           sudo ./install-bb
           rm install-bb
      - run: bb --version
      - name: Check for unused vars
        run: BABASHKA_CLASSPATH=src bin/bb-unused-vars -i .github/workflows/unused-vars-to-ignore.edn  bin/* src
      - name: Check for missed docstrings
        run: BABASHKA_CLASSPATH=src bin/bb-missed-docstrings -i 'cli-options|-main' bin/* src
